canary/canary/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path
from canary.views import register, sign_in, logout_view
from dbcanary.views import create_advert, CarView, advert_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path("register/", register, name="register"),
    path("auth/", sign_in, name="auth"),
    path("logout/", logout_view, name="logout"),
    path('', CarView.as_view(), name="showbill"),
    path("advert/<int:advert_id>", advert_view, name="car_details"),
    path('showbill/add/', create_advert, name="add_advert"),
]


if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

canary/dbcanary/models.py
from django.conf import settings
from django.db import models


ORDER_BY_CHOICES = (
    ("price_asc", "Price Asc"),
    ("price_desc", "Price Desc"),
)

CAR_MARK = (
    ("bmw", "BMW"),
    ("merc", "MERCEDES"),
    ("toyo", "TOYOTA"),
)


ENGINE_TYPE = (
    ("petr", "Petrol"),
    ("dies", "Diesel"),
    ("hyb", "Hybrid"),
    ("elec", "Electro"),
)


DRIVE = (
    ("fwd", "Front-wheel drive"),
    ("rwd", "Rear-wheel drive"),
    ("awd", "Automatic 4WD"),
    ("4wd", "Full-time 4WD"),
)


GEAR_BOX = (
    ("auto", "Automatic"),
    ("man", "Manual"),
)


class Advert(models.Model):
    engine_type = models.CharField(max_length=100, choices=ENGINE_TYPE, default="No type")
    engine_capacity = models.IntegerField(default="No capacity")
    drive = models.CharField(max_length=100, choices=DRIVE, default="No type")
    gear_box = models.CharField(max_length=100, choices=GEAR_BOX, default="No type")
    description = models.TextField(null=True, blank=True)
    image = models.ImageField(null=True, blank=True)
    win = models.CharField(max_length=17, null=True, blank=True)
    price = models.DecimalField(decimal_places=2, max_digits=15)
    price_usd = models.DecimalField(default=0, decimal_places=2, max_digits=15)
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="adverts"
    )
    phone_number = models.CharField(max_length=13)
    created_at = models.DateTimeField(auto_now_add=True, db_index=True,)
    favorites = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="favorite_adverts"
    )
    honey = models.CharField(max_length=200, default=None)


class Canary(models.Model):
    table = models.TextField(max_length=300)
    canary = models.CharField(max_length=500)

canary/templates/base.html
<!-- base.html -->
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="{% static "index.css" %}" rel="stylesheet">
    {% if messages %}
    {% endif %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
{% include "navbar.html" %}
<div class="container">
    {% block content %}{% endblock %}
</div>
{% block scripts %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous"></script>
{% endblock %}
<br><br>
<footer class="text-center text-white " style="background-color: #444444;">
    <!-- Grid container -->
    <div class="container p-0">
        <br>
        <!-- Section: CTA -->
        {% if request.user.is_authenticated %}
            <section class="glyphicon-log-out">
                <p class="d-flex justify-content-center align-items-center">
                    <span class="me-1">Logout</span>
                    <a href="{% url "logout" %}" class="btn btn-secondary btn-lg active" role="button"
                       aria-pressed="true">Logout</a>
                </p>
            </section>
        {% else %}
            <section class="register">
                <p class="d-flex justify-content-center align-items-center">
                    <span class="me-1">Register for free</span>
                    <a href="{% url "register" %}" class="btn btn-secondary btn-lg active" role="button"
                       aria-pressed="true">Sign UP</a>
                </p>
            </section>
        {% endif %}
        <!-- Section: CTA -->
    </div>
    <!-- Grid container -->
    <!-- Copyright -->
    <div class="text-center p-0" style="background-color: rgba(0, 0, 0, 0.2);">
        © 2022 Copyright:
        <a class="text-white" href="https://www.linkedin.com/in/artem-sheibak-a12923227/">Artem Sheibak</a>
    </div>
    <!-- Copyright -->
</footer>
</body>

</html>

canary/templates/car_card.html
{% load static %}

<div href="{% url 'car_details' advert.id %}" class="card mb-4">
    <div class="card-body">
        <h5 class="card-title">{{ advert.car.mark }}</h5>
        <h5 class="card-title">{{ advert.car.model.car_model }}</h5>
        {% if advert.image %}
            <img class="card-img-top mb-2" src="{{ advert.image.url}}" alt="{{ advert.car.mark }}">
        {% else %}
            <img src="{% static 'no-image.jpg' %}" class="card-img-top img-thumbnail" alt="No image">
        {% endif %}
        <h6 class="card-subtitle mb-2 text-muted">Cost: {{ advert.price }} BYN - {{ advert.price_usd }} USD</h6>
        <p class="card-engine"> Engine: {{ advert.get_engine_type_display }} - {{ advert.engine_capacity }}l.</p>
        <p class="card-transmission"> Transmission: {{ advert.get_gear_box_display }}</p>
        {% if advert.description %}
            <p class="card-text">{{ advert.description}}</p>
        {% endif %}
    </div>
</div>

canary/templates/car_details.html
{% extends "base.html" %}
{% load static %}
{% block title %} Advert {{ advert.car.model }}{% endblock %}
{% block content %}

    <main class="car-details">
        <h1 class="my-4">{{ advert.car.mark }} {{ advert.car.model.car_model }}</h1>
        <div class="row">
            <div class="col-4">
                {% if advert.image %}
                    <img src="{{ advert.image.url }}" alt="{{ advert.car.model }}" class="w-100">
                {% else %}
                    <img src="{% static 'no-image.jpg' %}" class="card-img-top img-thumbnail" alt="No image">
                {% endif %}
            </div>
            <div class="col-8">
                <h3 class="mb-3">Price: {{ advert.price }} BYN | {{ advert.price_usd }} USD</h3>
                <div class="mb-3">
                <h4 class="mb-3">Information: </h4>
                <h6 class="mb-3">Engine type: {{ advert.get_engine_type_display }}</h6>
                <h6 class="mb-3">Engine capacity: {{ advert.engine_capacity }} l.</h6>
                <h6 class="mb-3">Gear box: {{ advert.get_gear_box_display }}</h6>
                <h6 class="mb-3">Drive: {{ advert.get_drive_display }}</h6>
                <h6 class="mb-3">Win: {{ advert.win }}</h6>
                <h6 class="mb-3">Phone number: {{ advert.phone_number }}</h6>
                    <div class="description mb-3">
                    <h3 class="mb-3">Description:</h3>
                    <h6 class="mb-3" >{{ advert.description }}</h6>
                    </div>
                </div>
                {% if user.is_authenticated %}
                    <form method="POST" class="mt-4">
                        {% csrf_token %}
                        {% if is_advert_in_favorites %}
                            <input type="hidden" name="action" value="remove">
                            <button type="submit" class="btn btn-primary">Remove from favorites</button>
                        {% else %}
                            <input type="hidden" name="action" value="add">
                            <button type="submit" class="btn btn-primary">Add to favorites</button>
                        {% endif %}
                    </form>
                {% endif %}
            </div>
        </div>
    </main>
{% endblock %}

canary/templates/car_list.html
{% extends "base.html" %}
{% load pagination_tags%}
{% load i18n static crispy_forms_filters %}

{% block title %}Cars for sale{% endblock %}

{% block content %}
    <div class="cars">
        <h1 class="my-4">{% translate "Cars" %}</h1>
        <div class="row">
            <div class="col-3">
                <div class="filters-form mb-4">
                    <h3>{% translate "Filters" %}</h3>
                    <form class="form-inline">
                        {{ filters_form|crispy }}
                        <button type="submit" class="save btn btn-primary">{% translate "Search" %}</button>
                    </form>
                </div>
            </div>
            <nav class="col-9">
                <div class="row">
                    {% for advert in adverts %}
                        <div class="col-4">
                            {% include "car_card.html" %}
                        </div>
                    {% endfor %}
                </div>
            </nav>
            <nav aria-label="Page navigation example" class="my-3">
                <ul class="pagination justify-content-center">
                    {% if cars.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="{% url_replace page=1 %}">
                                &laquo; {% translate "First" %}
                            </a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="{% url_replace page=adverts.previous_page_number %}">
                                {% translate "Previous" %}
                            </a>
                        </li>
                    {% endif %}
                    <li class="page-item disabled">
                <span class="page-link">
                  {% translate "Page" %} {{ adverts.number }}
                  {% translate "of" %} {{ adverts.paginator.num_pages }}.
                </span>
                    </li>
                    {% if adverts.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="{% url_replace page=adverts.next_page_number %}">
                                {% translate "Next" %}
                            </a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="{% url_replace page=adverts.paginator.num_pages %}">
                                {% translate "Last" %} &raquo;
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>
{% endblock %}

canary/templates/create_advert.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>Add car advert</h1>
  <form enctype="multipart/form-data" method="POST" class="post-form">
    {% csrf_token %}
    {{ form_car | crispy }}
    {{ form | crispy }}
      <button type="submit" class="save btn btn-primary">Save</button>
  </form>
{% endblock %}

canary/templates/logout.html
{% extends "base.html" %}
{% block title %}Logged out{% endblock %}
{% block content %}
    <form action="" method="post"></form>
    <h1>Logged out</h1>
    <p>You have been successfully logged out. You can <a href="{% url "auth" %}">log-in again</a>.</p>
{% endblock %}

canary/templates/navbar.html
{% load static %}{% load tz %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <div class="navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url "add_advert" %}">Create advert</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url "logout" %}">Logout</a>
                    </li>
                {% else %}
                    <li>
                        <a class="nav-link active" aria-current="page" href="{% url "auth" %}">Login</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

canary/templates/register.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>Register user</h1>
  <form method="POST" class="post-form">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="save btn btn-primary">Save</button>
  </form>
{% endblock %}

canary/templates/sign_in.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>Authorise user</h1>
  <form method="POST" class="post-form">
    {% csrf_token %}
    {{ form | crispy}}
    <button type="submit" class="sign in btn btn-primary">Sign In</button>
  </form>
{% endblock %}